[en]
    languageName = "English (not yet available)"
    contentDir = "content/en"
    weight = 1
    [en.params.head]
        tagline = "A transit blog"
    [en.params.social]
        title = "Follow me"
        caption = "I work transport maps, just for fun!"
    [en.params.footer]
        # license = "Licensed under Creative Commons (<a href='https://creativecommons.org/licenses/by-nc-sa/4.0/' class='link-secondary' target='_blank' rel='noopener noreferrer'>CC BY-NC-SA 4.0</a>)."
[nl]
    languageName = "Nederlands"
    contentDir = "content/nl"
    weight = 1
    [nl.params.head]
        tagline = "A transit blog"
    [nl.params.social]
        title = "Volg me op m'n socials"
        caption = "Ik maak OV-kaarten, gewoon, omdat het kan!"
    [nl.params.footer]