baseURL = 'https://studiospoort.nl'
languageCode = 'nl-nl'
title = 'Studio Spoort'
theme = "plague"
defaultContentLanguage = 'nl'

[languages]
	[languages.nl]
	  contentDir = 'content/nl'
	  languageName = 'Nederlands'
	  weight = 1
	[languages.en]
	  contentDir = 'content/en'
	  languageName = 'English'
	  weight = 2

[module]
  [[module.imports]]
    disable = false
    ignoreConfig = false
    ignoreImports = true
    path = "github.com/brianreumere/plague"  # Theme
  [[module.imports]]
    disable = false
    ignoreConfig = false
    ignoreImports = true
    path = "github.com/gethugothemes/hugo-modules/images"

[params]
  siteHeaderText = "Studio Spoort"
  siteFooterText = """
© Studio Spoort 

{{ i18n "powered-by"}} [Hugo](https://gohugo.io/) and the [plague](https://github.com/brianreumere/plague) theme.
"""

  colors = "default"
  favicon = "images/icoon160pxs.png"

  [params.hcard]
    avatar = "images/icoon160px.png"
    fullName = "Jappie051"
    pronouns = [ "hij", "hem" ]
    nickname = "Jappie"
    showLocation = true
    city = "Eindhoven"
    region = "Noord-Brabant"
    country = "NL"

    social = [
      { platform = "email", identity = "jappie051@gmail.com", url_pattern = "mailto:%s" },
      { platform = "github", identity = "Jappie051", url_pattern = "https://github.com/%s" }
    ]

[[params.plugins.js]]
link = "plugins/lazy-loader.js"

[markup.goldmark.renderer]
unsafe = true