[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "labels"
  pageRef = "/tags"
  weight = 20

[[social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/Jappie051"
  weight = 20

# toml-docs-start sample-navigation
[[sample]]
  name = "Blog"
  pageRef = "/blog/"
  weight = 10

[[sample]]
  name = "Projects"
  pageRef = "/projects/"
  weight = 20

# toml-docs-end sample-navigation